### ISSUE TITLE
Support for ad metadata

### ISSUE THREAD

**Issue by dyue** [bitmovin/bitmovin-player-android-analytics-conviva#47]
Would like to attach ad metadata during ad break started/ad started.   From looking at the Conviva classes, this is done via ConvivaAdAnalytics instead of ConvivaVideoAnalytics.

**Comment by strangesource** [comment]
This is supported with the latest release https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/releases/tag/v2.4.0
